### ISSUE TITLE
AssertNil will blow up

### ISSUE THREAD

**Issue by Netherdrake** [ivpusic/neo#11]
Doing this does blow up sometimes:

```
	app.Get("/downloads", func(ctx *neo.Ctx) {
		data, err := util.FolderScanner(util.RelativePath("tmp"), util.File)
		neo.AssertNil(err, http.StatusNoContent, []byte(err.Error()))
		ctx.Res.Json(data, http.StatusOK)
	})
```

If there is no error
```
neo.AssertNil(err, http.StatusNoContent, []byte(err.Error()))
```
Will cause nil pointer panic.

**Comment by ivpusic** [comment]
I know for this issue. First I was thinking about making different wrappers for specific cases...for example something like....neo.AssertNilError(err, 400), and then internally check if err is != nil and then (maybe) call again neo.AssertNil......but there can be a lot of specific cases to handle...so I decided just to provide basic methods for assertions, and leave users to define their specific wrappers if they need them.

**Comment by Netherdrake** [comment]
Maybe we should add a 'default' wrapper as an option aka:
```
neo.AssertNil(err, http.StatusNoContent, neo.Error(err)))
```

Or teach people how to make a wrapper in documentation.

**Comment by ivpusic** [comment]
hmm...I am just thinking...maybe would be good to cover this case from our side, because checking if err is != nil and returning err.Error() is common.

So my proposal would be something like:
```Go
// if err != nil {
//   neo.Assert(false, 400, []byte(err.Error()))
// }
//

// actual wrapper
neo.AssertNilErr(err, 400)
```

**Comment by Netherdrake** [comment]
That is very concise and probably covers most of use cases.

I would however add 1 more argument to it.
```
neo.AssertNilErr(err, 400, neo.Json)
```

So user can pick how to return it, text, json, xml, whatever. neo.Json in this case is just a pre-defined constant.

So if its json, it would return something like this:
{ error: "err.Error here"}

**Comment by ivpusic** [comment]
Hm, introducing new constants like neo.Json, neo.Xml, etc. is maybe too much.

Let's make it simple, just return text/plain in case of ``AsserNilErr``. I will do it.

**Comment by Netherdrake** [comment]
Well, if you have a JSON api, returniing text/plain is kind of weird.

**Comment by Netherdrake** [comment]
Hey, what if instead of giving `AssertNilErr` the response content type manually, the default could be set for the whole application.

This default could then be used to produce the correct response on all types of errors (assertions, 404s, etc).

**Comment by ivpusic** [comment]
Second suggestion sounds really good, so format will be based on ``accept content type`` header. Do you have some time to do that? And updating docs with new feature would be cool.

**Comment by Netherdrake** [comment]
Unfortunately I can't do it at this time. 

But as long as those helper methods (like AssertNilErr) have access to `req.headers` it should be easy.

You just listen to `Accept` header:
```
Accept:application/json, text/plain, */*
```
Its usually high priority first, lower priority later, so you just scan it and reply with the first supported protocol.
