### ISSUE TITLE
Why shell-script?

### ISSUE THREAD

**Issue by mattn** [ivpusic/neo#13]
I want to try neo on Windows.  But currently, neo/scripts is written in bash. So not possible.

https://github.com/ivpusic/neo/tree/master/cmd/neo/scripts

**Comment by ivpusic** [comment]
it is on my TODO list to rewrite scripts in go.

**Comment by mattn** [comment]
> it is on my TODO list to rewrite scripts in go.

Cool!

**Comment by ivpusic** [comment]
Neo should work on windows now.  Done by https://github.com/ivpusic/neo/commit/5ecca2105fe86d374698383d9d65ffa9bf727868 and https://github.com/ivpusic/go-hotreload/commit/58dd58cfd70b15aa9db4588546667633db399233.

Please report issues if you have any. Thank you!

**Comment by mattn** [comment]
Good to hear! :+1:
