### ISSUE TITLE
how to get wildcard param's value?

### ISSUE THREAD

**Issue by butaixianran** [ivpusic/neo#18]
We need something like this:

```` go
	app.Get("/path/:name/*", func(c *neo.Ctx) (int, error) {
		others := c.Req.Params("*")
		//do something
	})
````

How can I get the value of wildcard? Thanks

p.s. neo is great, it's exactly what we need, its router is also much easy to use then gin and echo. Thanks for this great job

**Comment by butaixianran** [comment]
I create a pull request to "ivpusic/urlregex" to support named wildcards, which also works for neo just fine.

**Comment by ivpusic** [comment]
Awesome! Thanks a lot for this. So far I didn't need this feature so it is missing right now. Check out comment I put on your pull request, so we can merge it.

**Comment by ivpusic** [comment]
https://github.com/ivpusic/urlregex/pull/1#issuecomment-175918984 merged. Thanks again.
