### ISSUE TITLE
Is there a place to put all middlewares together?

### ISSUE THREAD

**Issue by butaixianran** [ivpusic/neo#20]
So users of neo can get them more easily. maybe a list on a wiki page?

**Comment by ivpusic** [comment]
Currently there is not central place where users take take a look into available middlewares. Probably I should add section to gh-pages to include that list.

Currently public middlewares I did are:
- https://github.com/ivpusic/neo/tree/master/middlewares/logger
- https://github.com/ivpusic/neo-cors

**Comment by butaixianran** [comment]
Since there is no central place for mw, I may just put them here.


* [jwt](https://github.com/diankong/neomw/tree/master/jwt)
* [try catch](https://github.com/diankong/neomw/tree/master/trier)

**Comment by ivpusic** [comment]
I created contrib section for neo contrib. You can find it here http://ivpusic.github.io/neo/contrib/2016/02/18/contrib.html.
