### ISSUE TITLE
neo cli  run main.go won't work

### ISSUE THREAD

**Issue by butaixianran** [ivpusic/neo#23]
Will get this panic:
panic: template: application-build-1454079793108505400.exe:1887: unexpected unrecognized character in action: U+FFFD '�' in command

There're many useless characters in log, which can not be displayed correctly on windows and get panic.

could we just remove them?

**Comment by ivpusic** [comment]
yes, we should remove then in case of windows if they arw causing troubles. neo is using golog, so change should be done there.

**Comment by butaixianran** [comment]
@ivpusic  I test it on linux and get the same panic:
````
panic: template: application-build-1454081918419024649:116: unexpected unrecognized character in action: U+0002 in command

goroutine 1 [running]:
github.com/ivpusic/neo.compileTpl(0xc82016df00, 0x1, 0x1)
        /home/ubuntu/workspace/src/github.com/ivpusic/neo/template.go:66 +0x34a
github.com/ivpusic/neo.(*Application).Templates(0xc820157700, 0xc82016df00, 0x1, 0x1)
        /home/ubuntu/workspace/src/github.com/ivpusic/neo/application.go:157 +0x35
main.main()
        /home/ubuntu/workspace/src/neotest/myapp/main.go:20 +0x1c6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
````

**Comment by butaixianran** [comment]
get some detail with fmt.Println:
````
path:  *
pths:  [application-build-1454083006486300000.exe config.toml index.tpl main.go]
locations:  [application-build-1454083006486300000.exe config.toml index.tpl main.go]
panic: template: application-build-1454083006486300000.exe:265: unexpected unrecognized character in action: U+0000 in command
````

not sure how to fix it.

**Comment by butaixianran** [comment]
Seems, 
template.ParseFiles() 
need a template file name, but in "main.go" create by "neo" cli, set a line like this:
````Go
app.Templates("*")
````
Which offers every file to template.ParseFiles.
change it to app.Templates("index") will fix this.
pull request will be on the way...

**Comment by butaixianran** [comment]
would you please merge them? thanks.

**Comment by ivpusic** [comment]
Merged. will close this one
