### ISSUE TITLE
would we change the color of document site?

### ISSUE THREAD

**Issue by butaixianran** [ivpusic/neo#25]
From dark theme into some bright theme, for example:

![][1]

Sure dark theme is better for eyes, but bright theme make it looks more modern. I've already changed it in my fork, if it's ok to you, I'll create a pull request.

  [1]: https://lh3.googleusercontent.com/JC-da4MrNcFb8N0O2AMEyniBd8Yq6opL8593ccezaMD_33zUueTaugL0MQSfJKtdP3A=w1366-h768-rw-no

**Comment by ivpusic** [comment]
+1
