### ISSUE TITLE
Can we remove gorm from ctx?

### ISSUE THREAD

**Issue by butaixianran** [ivpusic/neo#26]
I try to recommand neo to other people and they don't think gorm should be in ctx, which many people may never use it at all.

I know it's a break change, but that's make sense for a lightweight web frame. Even who need gorm, they may never use it in a route handle function. They must have some model, controller packages for that.

**Comment by ivpusic** [comment]
+1 for this. Probably trying to force users to use gorm is not that good idea. I can remove it, but on tuesday...until then I am just on my mobile

**Comment by butaixianran** [comment]
I'll do it

**Comment by ivpusic** [comment]
Merged. I have to think about some strategies for doing db transaction rollback. Probably I will update middleware api in a way that calling next() returns error if happened in previous middleware or route handler. Do you have some suggestions?

**Comment by butaixianran** [comment]
I've created a try catch middleware for neo, which may work for this after some modification. Call a rollback function in catch section, for example.

But neo do need a good way to handle errors, not just for rollback.

What gin does is: add an Error(err) func to ctx, which append error to  
ctx.errMsgs []*Error

So a middleware can handle it later.
[more detail](https://godoc.org/github.com/gin-gonic/gin#Context.Error)

Seems neo's ctx doesn't have something like this for now.

**Comment by ivpusic** [comment]
Hmm, collecting errors into request context sounds interesting. I will think about that. Tnx for suggestion
