### ISSUE TITLE
Can neo has Region params like gin‘s Group

### ISSUE THREAD

**Issue by ElvizLai** [ivpusic/neo#35]
Ex:
```
app:=neo.App()
g:=app.Region(“/admin”)
g.Use(xxx)
g.Get("/list",List)
```

the router should be "/admin/list",and use middle xxx

**Comment by ivpusic** [comment]
Feature added in https://github.com/ivpusic/neo/commit/352f5dfa7925a1e740ac67736b93679befb085ee. So Region without prefix is still default option. If you want some default prefix for region, use `RegionWithPrefix` and provide prefix as argument.

**Comment by ivpusic** [comment]
Update: just added docs with example how to use this feature. Check it out here http://ivpusic.github.io/neo/tutorials/2015/01/22/regions.html#region-with-default-prefix
