### ISSUE TITLE
Can not create skeleton using 'neo new'.

### ISSUE THREAD

**Issue by shawnye** [ivpusic/neo#40]
<pre>
e:\WORKSPACE>neo new spim
 git/ivp/neo 17:29:24 ✖[ERRO] ▶ exit status 1
</pre>

**Comment by shawnye** [comment]
I found the reason:
It fail to download and compile source from : 
github.com/ivpusic/rerun

**Comment by ivpusic** [comment]
@shawnye does it work for you now? it should be able to fetch rerun

**Comment by shawnye** [comment]
yes ,it worked.
The reason for that is the network interruption causing the absence of  the `github.com/ivpusic/rerun` source
