### ISSUE TITLE
Use cases for event functionality

### ISSUE THREAD

**Issue by joeblew99** [ivpusic/neo#41]
I have not seen a golang web framework that has events like this does.

I was looking for examples to see how and its use cases. Are there any ?

Also it seem to use a bus. Pretty smart.

Very curious and if you have more info / URLs please let me know

**Comment by ivpusic** [comment]
I have node.js background, so node.je was one of inspirations for this framework, and that's one of tje main reasons why this framework has events. One of use cases for events can be centralized error handling.

**Comment by joeblew99** [comment]
Ok thanks
