### ISSUE TITLE
Neo cli to restart on static file changes

### ISSUE THREAD

**Issue by azzuwan** [ivpusic/neo#42]
Is there anyway to just use neo cli to detect changes in all the files in the project? I love Neo and it's Express like architecture!

**Comment by ivpusic** [comment]
you can provide configuration file. Example here http://ivpusic.github.io/neo/tutorials/2015/01/22/configuration.html ("suffixes" is option you need). Under the hood neo is using https://github.com/ivpusic/rerun, so you can get more info about suffixes here
