### ISSUE TITLE
Remove "neo" topic from repo

### ISSUE THREAD

**Issue by revett** [ivpusic/neo#48]
### Problem

The NEO blockchain team have created an official page for the `neo` topic on Github.

See here: https://github.com/topics/neo

This repo has added the `neo` topic however it isn't relevant as a topic, more just as a name.

### Solution

Remove `neo` topic from repo.

### Notes

- None

**Comment by ivpusic** [comment]
it is name of a web framework, which is relevant to this repo

**Comment by revett** [comment]
`name !== topic` 

¯\_(ツ)_/¯
