### ISSUE TITLE
cannot create directory at 'aux'

### ISSUE THREAD

**Issue by dc0d** [ivpusic/neo#6]
When git wants to checkout it will show this error: `fatal: cannot create directory at 'aux': Invalid argument`. That's because `aux` is a reserved name on Windows.

**Comment by ivpusic** [comment]
Unfortunately I don't have and I don't use windows, but adding support for it would be great. Are you interested in contributing by adding support for win? 

I think currently "aux" issue is the problem, and https://github.com/ivpusic/go-hotreload/blob/master/hr/pm.go#L21 "fuser" Unix specific command used by "go-hotreload" package.

**Comment by ivpusic** [comment]
http://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows -> this may be solution for "fuser" Unix command. And renaming aux and testing it should be trivial.

**Comment by dc0d** [comment]
Thanks for the nice neo! I've already forked neo and as soon as I feel happy about it (naturally restricted to my mind-frame & abilities) I'll make a pull request. The problem is the only way around it (AFAIK) is to use a name like `_aux` or `misc` instead of `aux`.

**Comment by ivpusic** [comment]
I refactored aux package. Look at https://github.com/ivpusic/neo/commit/c810caf4bcb013516921fd6342012f91e80c51e7. So next step is to solve "fuser" thing on win.

**Comment by dc0d** [comment]
Thanks; I was thinking not everybody would be comfortable with renaming.

**Comment by dc0d** [comment]
I am not experiencing any problem with neo. But I've not tested the command line (thanks to the stork in charge of delivering me, around my area internet is a messed up thing - i.e. no access to gopkg; in this case, on the other end. But I'm on it). So this issue should be closed and `fuser` should be handled on another issue. I'll follow up the thing, but `fuser` should be handled in a very different way on Windows - watchers and the like; I've not used it ever either.

**Comment by ivpusic** [comment]
Yes, ``fuser`` issue is related to Neo hotreload (``neo run main.go``).

Thanks for reporting this one!
