### ISSUE TITLE
static files serve broken

### ISSUE THREAD

**Issue by xi3** [ivpusic/neo#8]
git/ivp/neo 09:20:51 ♥[INFO] ▶ --> [Req] HEAD to /static/multipage/images/portfolio/6@2x.jpg
 git/ivp/neo 09:20:51 ♥[INFO] ▶ <-- [Res] (404) HEAD to /static/multipage/images/portfolio/6@2x.jpg Took 0
 git/ivp/neo 09:20:51 ★[DEBU] ▶ trying to match static url: /static/multipage/images/portfolio/7@2x.jpg
 git/ivp/neo 09:20:51 ★[DEBU] ▶ replacing /static/multipage/images/portfolio/7@2x.jpg with /static
 git/ivp/neo 09:20:51 ★[DEBU] ▶ found possible result. Path: /home/xi/go/src/github.com/xi3/yishu/public/multipage/images/portfolio/7@2x.jpg
 git/ivp/neo 09:20:51 ★[DEBU] ▶ replacing /static/multipage/images/portfolio/5@2x.jpg with /static
 git/ivp/neo 09:20:51 ★[DEBU] ▶ found possible result. Path: /home/xi/go/src/github.com/xi3/yishu/public/multipage/images/portfolio/5@2x.jpg
 git/ivp/neo 09:20:51 ★[DEBU] ▶ result not found in static
 git/ivp/neo 09:20:51 ★[DEBU] ▶ route /static/multipage/images/portfolio/5@2x.jpg not found
 git/ivp/neo 09:20:51 ♥[INFO] ▶ --> [Req] HEAD to /static/multipage/images/portfolio/5@2x.jpg
 git/ivp/neo 09:20:51 ♥[INFO] ▶ <-- [Res] (404) HEAD to /static/multipage/images/portfolio/5@2x.jpg Took 0
 git/ivp/neo 09:20:51 ★[DEBU] ▶ trying to match static url: /static/multipage/images/portfolio/8@2x.jpg
 git/ivp/neo 09:20:51 ★[DEBU] ▶ replacing /static/multipage/images/portfolio/8@2x.jpg with /static
 git/ivp/neo 09:20:51 ★[DEBU] ▶ found possible result. Path: /home/xi/go/src/github.com/xi3/yishu/public/multipage/images/portfolio/8@2x.jpg
 git/ivp/neo 09:20:51 ★[DEBU] ▶ result not found in static
 git/ivp/neo 09:20:51 ★[DEBU] ▶ route /static/multipage/images/portfolio/8@2x.jpg not found
 git/ivp/neo 09:20:51 ♥[INFO] ▶ --> [Req] HEAD to /static/multipage/images/portfolio/8@2x.jpg
 git/ivp/neo 09:20:51 ♥[INFO] ▶ <-- [Res] (404) HEAD to /static/multipage/images/portfolio/8@2x.jpg Took 0
2015/02/21 09:20:51 http: panic serving 60.252.32.245:59490: tabwriter: panic during Write
goroutine 37 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/ivpusic/neo.func·001()
	/home/xi/go/src/github.com/ivpusic/neo/application.go:55 +0x95
github.com/ivpusic/neo.func·002()
	/home/xi/go/src/github.com/ivpusic/neo/application.go:77 +0x13d
text/tabwriter.handlePanic(0xc20813f468, 0x7e1270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.handlePanic(0xc20813f350, 0x7db270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.(*Writer).writeLines(0xc2080be200, 0x0, 0x0, 0x2, 0xab)
	/usr/local/go/src/text/tabwriter/tabwriter.go:262 +0x70f
text/tabwriter.(*Writer).format(0xc2080be200, 0x0, 0x0, 0x2, 0x9e3928)
	/usr/local/go/src/text/tabwriter/tabwriter.go:370 +0x421
text/tabwriter.(*Writer).Flush(0xc2080be200, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:466 +0xfc
text/tabwriter.(*Writer).Write(0xc2080be200, 0xc2080ef0e0, 0xac, 0x120, 0xac, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:501 +0x4a3
fmt.Fprintln(0x7f182009b058, 0xc2080be200, 0xc20813f580, 0x1, 0x1, 0x83, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:255 +0x9f
github.com/ivpusic/go-clicolor/clicolor.(*Printer).InFormat(0xc2080d8220)
	/home/xi/go/src/github.com/ivpusic/go-clicolor/clicolor/clicolor.go:56 +0x50f
github.com/ivpusic/golog.(*Stdout).Append(0xc20801e540, 0xecc79d473, 0x2a801648, 0x9db0c0, 0xc208150ee0, 0x6c, 0xa, 0x7e3e70, 0x4, 0x7f8310, ...)
	/home/xi/go/src/github.com/ivpusic/golog/appender.go:50 +0x3ed
github.com/ivpusic/golog.(*Logger).makeLog(0xc208010150, 0x6d4780, 0xc2080d8190, 0xa, 0x7e3e70, 0x4, 0x7f8310, 0x3, 0x7da150, 0x5, ...)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:139 +0x215
github.com/ivpusic/golog.(*Logger).Debug(0xc208010150, 0x6d4780, 0xc2080d8190, 0x0, 0x0, 0x0)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:241 +0xc5
github.com/ivpusic/neo.(*Static).match(0xc208038208, 0xc20806c5c5, 0x2b, 0x0, 0x0, 0x0, 0x0)
	/home/xi/go/src/github.com/ivpusic/neo/static.go:38 +0x593
github.com/ivpusic/neo.(*Application).ServeHTTP(0xc20806c480, 0x7f182009c750, 0xc2080940a0, 0xc208034750)
	/home/xi/go/src/github.com/ivpusic/neo/application.go:87 +0x1ee
net/http.serverHandler.ServeHTTP(0xc2080bd2c0, 0x7f182009c750, 0xc2080940a0, 0xc208034750)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208116320)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
 git/ivp/neo 09:20:51 ★[DEBU] ▶ emmiting event `error`
 git/ivp/neo 09:20:51 ★[DEBU] ▶ trying to match static url: /static/multipage/images/portfolio/9@2x.jpg
 git/ivp/neo 09:20:51 ★[DEBU] ▶ listeners for event error not found git/ivp/neo 09:20:51 ★[DEBU] ▶ listeners for event error 
 git/ivp/neo 09:20:51 ★[DEBU] ▶ emmiting event `error`
panic: runtime error: index out of range [recovered]
	panic: tabwriter: panic during Flush [recovered]
	panic: tabwriter: panic during Write

goroutine 39 [running]:
text/tabwriter.handlePanic(0xc2081419c8, 0x7e1270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.handlePanic(0xc2081418b0, 0x7db270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.(*Writer).writeLines(0xc2080be200, 0x0, 0x0, 0x2, 0x55)
	/usr/local/go/src/text/tabwriter/tabwriter.go:262 +0x70f
text/tabwriter.(*Writer).format(0xc2080be200, 0x0, 0x0, 0x2, 0x9e3928)
	/usr/local/go/src/text/tabwriter/tabwriter.go:370 +0x421
text/tabwriter.(*Writer).Flush(0xc2080be200, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:466 +0xfc
text/tabwriter.(*Writer).Write(0xc2080be200, 0xc2080a2b80, 0x56, 0x80, 0x56, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:501 +0x4a3
fmt.Fprintln(0x7f182009b058, 0xc2080be200, 0xc208141ae0, 0x1, 0x1, 0x2d, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:255 +0x9f
github.com/ivpusic/go-clicolor/clicolor.(*Printer).InFormat(0xc20813aa10)
	/home/xi/go/src/github.com/ivpusic/go-clicolor/clicolor/clicolor.go:56 +0x50f
github.com/ivpusic/golog.(*Stdout).Append(0xc20801e540, 0xecc79d473, 0x2aefc091, 0x9db0c0, 0xc20812cfe0, 0x16, 0xa, 0x7e3e70, 0x4, 0x7f8310, ...)
	/home/xi/go/src/github.com/ivpusic/golog/appender.go:50 +0x3ed
github.com/ivpusic/golog.(*Logger).makeLog(0xc208010150, 0x6d4780, 0xc20813a990, 0xa, 0x7e3e70, 0x4, 0x7f8310, 0x3, 0x7da150, 0x5, ...)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:139 +0x215
github.com/ivpusic/golog.(*Logger).Debugf(0xc208010150, 0x828210, 0x13, 0xc208141f80, 0x1, 0x1)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:277 +0x137
github.com/ivpusic/neo/ebus.func·001()
	/home/xi/go/src/github.com/ivpusic/neo/ebus/ebus.go:40 +0x130
created by github.com/ivpusic/neo/ebus.(*EBus).Emit
	/home/xi/go/src/github.com/ivpusic/neo/ebus/ebus.go:52 +0x124

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc208074920, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208074920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080748c0, 0x0, 0x7f182009ae60, 0xc2080d8c08)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080383d8, 0x4a82ee, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2080383d8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2080bd2c0, 0x7f182009c598, 0xc2080383d8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2080bd2c0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20802afb0, 0x5, 0x7f182009b4d0, 0xc20806c480, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1808 +0xba
github.com/ivpusic/neo.(*Application).Start(0xc20806c480)
	/home/xi/go/src/github.com/ivpusic/neo/application.go:127 +0x197
main.main()
	/home/xi/go/src/github.com/xi3/yishu/main.go:29 +0x319

goroutine 34 [IO wait]:
net.(*pollDesc).Wait(0xc208145090, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208145090, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208145030, 0xc208135000, 0x1000, 0x1000, 0x0, 0x7f182009ae60, 0xc20813a308)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038680, 0xc208135000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208152cc8, 0xc208135000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080deb80, 0xc208135000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2080bd920)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2080bd920, 0xc2080c3b0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2080bd920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080eb410, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080eb410, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2080bd920, 0xc208035040, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208152c80, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208152c80)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 35 [IO wait]:
net.(*pollDesc).Wait(0xc20815b640, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20815b640, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20815b5e0, 0xc208155000, 0x1000, 0x1000, 0x0, 0x7f182009ae60, 0xc2080d8f38)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038588, 0xc208155000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208116728, 0xc208155000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20812cf40, 0xc208155000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2080bd560)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2080bd560, 0xc2080c5b0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2080bd560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080cf380, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080cf380, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2080bd560, 0xc208035110, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2081166e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2081166e0)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 33 [IO wait]:
net.(*pollDesc).Wait(0xc208145020, 0x77, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc208145020, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:93 +0x43
net.sendFile(0xc208144fc0, 0x7f182009ae10, 0xc208038c08, 0x6e0a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/sendfile_linux.go:60 +0x40c
net.(*TCPConn).ReadFrom(0xc208038678, 0x7f182009c6a8, 0xc2080788e0, 0xc, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:69 +0x57
net/http.(*response).ReadFrom(0xc208117900, 0x7f182009c6a8, 0xc2080788e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:413 +0x432
io.Copy(0x7f182009cc68, 0xc208117900, 0x7f182009c6a8, 0xc2080788e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
io.CopyN(0x7f182009cc68, 0xc208117900, 0x7f182009ae10, 0xc208038c08, 0x5ab7a7, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x113
net/http.serveContent(0x7f182009c750, 0xc208117900, 0xc208035520, 0xc20804e8fd, 0xa, 0xecc79cf9a, 0x128e55af, 0x9db0c0, 0xc2080c76d8, 0x7f182009cab0, ...)
	/usr/local/go/src/net/http/fs.go:257 +0xb33
net/http.serveFile(0x7f182009c750, 0xc208117900, 0xc208035520, 0x7f182009c810, 0xc20813af30, 0xc208139cad, 0xa, 0x0)
	/usr/local/go/src/net/http/fs.go:412 +0x7dd
net/http.ServeFile(0x7f182009c750, 0xc208117900, 0xc208035520, 0xc208139c70, 0x47)
	/usr/local/go/src/net/http/fs.go:428 +0xf1
github.com/ivpusic/neo.(*Response).serveFile(0xc208122120, 0xc208139c70, 0x47)
	/home/xi/go/src/github.com/ivpusic/neo/response.go:126 +0x144
github.com/ivpusic/neo.func·003(0xc20814cc80)
	/home/xi/go/src/github.com/ivpusic/neo/application.go:92 +0x45
github.com/ivpusic/neo.handler.apply(0xc2080dfae0, 0xc20814cc80, 0xc2080dfb00, 0x2, 0x2, 0x1)
	/home/xi/go/src/github.com/ivpusic/neo/router.go:16 +0x2d
github.com/ivpusic/neo.func·006()
	/home/xi/go/src/github.com/ivpusic/neo/interceptor.go:24 +0xa0
github.com/ivpusic/neo/middlewares/logger.Log(0xc20814cc80, 0xc2080dfb60)
	/home/xi/go/src/github.com/ivpusic/neo/middlewares/logger/logger.go:21 +0x185
github.com/ivpusic/neo.middleware.apply(0x8a7890, 0xc20814cc80, 0xc2080dfb00, 0x2, 0x2, 0x0)
	/home/xi/go/src/github.com/ivpusic/neo/interceptor.go:26 +0x135
github.com/ivpusic/neo.(*middleware).apply(0xc208038230, 0xc20814cc80, 0xc2080dfb00, 0x2, 0x2, 0x0)
	<autogenerated>:58 +0xc7
github.com/ivpusic/neo.func·005(0xc20814cc80)
	/home/xi/go/src/github.com/ivpusic/neo/interceptor.go:12 +0x7d
github.com/ivpusic/neo.(*Application).ServeHTTP(0xc20806c480, 0x7f182009c750, 0xc208117900, 0xc208035520)
	/home/xi/go/src/github.com/ivpusic/neo/application.go:96 +0x46b
net/http.serverHandler.ServeHTTP(0xc2080bd2c0, 0x7f182009c750, 0xc208117900, 0xc208035520)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208152be0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 31 [IO wait]:
net.(*pollDesc).Wait(0xc2080d23e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080d23e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080d2380, 0xc208073000, 0x1000, 0x1000, 0x0, 0x7f182009ae60, 0xc2080d9cb0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038820, 0xc208073000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208033b28, 0xc208073000, 0x1000, 0x1000, 0xc00000000000002, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080d6e60, 0xc208073000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081227e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081227e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081227e0, 0x0, 0x0, 0x0, 0xc207ff3100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080cea50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080cea50, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081227e0, 0xc2080349c0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208033ae0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208033ae0)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 32 [semacquire]:
sync.(*Mutex).Lock(0xc20804e0a0)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
log.(*Logger).Output(0xc20804e0a0, 0x2, 0xc208162100, 0xa1c, 0x0, 0x0)
	/usr/local/go/src/log/log.go:134 +0x97
log.Printf(0x84b850, 0x1d, 0xc208142c78, 0x3, 0x3)
	/usr/local/go/src/log/log.go:276 +0x87
net/http.(*Server).logf(0xc2080bd2c0, 0x84b850, 0x1d, 0xc208142c78, 0x3, 0x3)
	/usr/local/go/src/net/http/server.go:1775 +0x8b
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1131 +0x24f
github.com/ivpusic/neo.func·001()
	/home/xi/go/src/github.com/ivpusic/neo/application.go:55 +0x95
github.com/ivpusic/neo.func·002()
	/home/xi/go/src/github.com/ivpusic/neo/application.go:77 +0x13d
text/tabwriter.handlePanic(0xc208143468, 0x7e1270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.handlePanic(0xc208143350, 0x7db270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.(*Writer).writeLines(0xc2080be200, 0x0, 0x0, 0x3, 0x55)
	/usr/local/go/src/text/tabwriter/tabwriter.go:262 +0x70f
text/tabwriter.(*Writer).format(0xc2080be200, 0x0, 0x0, 0x3, 0x9e3928)
	/usr/local/go/src/text/tabwriter/tabwriter.go:370 +0x421
text/tabwriter.(*Writer).Flush(0xc2080be200, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:466 +0xfc
text/tabwriter.(*Writer).Write(0xc2080be200, 0xc208032aa0, 0x87, 0xa0, 0x87, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:501 +0x4a3
fmt.Fprintln(0x7f182009b058, 0xc2080be200, 0xc208143580, 0x1, 0x1, 0x5e, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:255 +0x9f
github.com/ivpusic/go-clicolor/clicolor.(*Printer).InFormat(0xc20813a3b0)
	/home/xi/go/src/github.com/ivpusic/go-clicolor/clicolor/clicolor.go:56 +0x50f
github.com/ivpusic/golog.(*Stdout).Append(0xc20801e540, 0xecc79d473, 0x2ad1e1d0, 0x9db0c0, 0xc20804e730, 0x47, 0xa, 0x7e3e70, 0x4, 0x7f8310, ...)
	/home/xi/go/src/github.com/ivpusic/golog/appender.go:50 +0x3ed
github.com/ivpusic/golog.(*Logger).makeLog(0xc208010150, 0x6d4780, 0xc20813b590, 0xa, 0x7e3e70, 0x4, 0x7f8310, 0x3, 0x7da150, 0x5, ...)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:139 +0x215
github.com/ivpusic/golog.(*Logger).Debug(0xc208010150, 0x6d4780, 0xc20813b590, 0x0, 0x0, 0x0)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:241 +0xc5
github.com/ivpusic/neo.(*Static).match(0xc208038208, 0xc208128305, 0x2b, 0x0, 0x0, 0x0, 0x0)
	/home/xi/go/src/github.com/ivpusic/neo/static.go:22 +0x100
github.com/ivpusic/neo.(*Application).ServeHTTP(0xc20806c480, 0x7f182009c750, 0xc208032a00, 0xc208034dd0)
	/home/xi/go/src/github.com/ivpusic/neo/application.go:87 +0x1ee
net/http.serverHandler.ServeHTTP(0xc2080bd2c0, 0x7f182009c750, 0xc208032a00, 0xc208034dd0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208152b40)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 37 [runnable]:
syscall.Syscall(0x1, 0x2, 0xc2080b6800, 0xa31, 0xa31, 0xa31, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.write(0x2, 0xc2080b6800, 0xa31, 0x1800, 0xc2080b6800, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1263 +0x6e
syscall.Write(0x2, 0xc2080b6800, 0xa31, 0x1800, 0x1800, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:152 +0x58
os.(*File).write(0xc208038010, 0xc2080b6800, 0xa31, 0x1800, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:212 +0xb7
os.(*File).Write(0xc208038010, 0xc2080b6800, 0xa31, 0x1800, 0x9db0c0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:139 +0x91
log.(*Logger).Output(0xc20804e0a0, 0x2, 0xc208160b00, 0xa1d, 0x0, 0x0)
	/usr/local/go/src/log/log.go:153 +0x4ed
log.Printf(0x84b850, 0x1d, 0xc20813ec78, 0x3, 0x3)
	/usr/local/go/src/log/log.go:276 +0x87
net/http.(*Server).logf(0xc2080bd2c0, 0x84b850, 0x1d, 0xc20813ec78, 0x3, 0x3)
	/usr/local/go/src/net/http/server.go:1775 +0x8b
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1131 +0x24f
github.com/ivpusic/neo.func·001()
	/home/xi/go/src/github.com/ivpusic/neo/application.go:55 +0x95
github.com/ivpusic/neo.func·002()
	/home/xi/go/src/github.com/ivpusic/neo/application.go:77 +0x13d
text/tabwriter.handlePanic(0xc20813f468, 0x7e1270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.handlePanic(0xc20813f350, 0x7db270, 0x5)
	/usr/local/go/src/text/tabwriter/tabwriter.go:443 +0x126
text/tabwriter.(*Writer).writeLines(0xc2080be200, 0x0, 0x0, 0x2, 0xab)
	/usr/local/go/src/text/tabwriter/tabwriter.go:262 +0x70f
text/tabwriter.(*Writer).format(0xc2080be200, 0x0, 0x0, 0x2, 0x9e3928)
	/usr/local/go/src/text/tabwriter/tabwriter.go:370 +0x421
text/tabwriter.(*Writer).Flush(0xc2080be200, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:466 +0xfc
text/tabwriter.(*Writer).Write(0xc2080be200, 0xc2080ef0e0, 0xac, 0x120, 0xac, 0x0, 0x0)
	/usr/local/go/src/text/tabwriter/tabwriter.go:501 +0x4a3
fmt.Fprintln(0x7f182009b058, 0xc2080be200, 0xc20813f580, 0x1, 0x1, 0x83, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:255 +0x9f
github.com/ivpusic/go-clicolor/clicolor.(*Printer).InFormat(0xc2080d8220)
	/home/xi/go/src/github.com/ivpusic/go-clicolor/clicolor/clicolor.go:56 +0x50f
github.com/ivpusic/golog.(*Stdout).Append(0xc20801e540, 0xecc79d473, 0x2a801648, 0x9db0c0, 0xc208150ee0, 0x6c, 0xa, 0x7e3e70, 0x4, 0x7f8310, ...)
	/home/xi/go/src/github.com/ivpusic/golog/appender.go:50 +0x3ed
github.com/ivpusic/golog.(*Logger).makeLog(0xc208010150, 0x6d4780, 0xc2080d8190, 0xa, 0x7e3e70, 0x4, 0x7f8310, 0x3, 0x7da150, 0x5, ...)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:139 +0x215
github.com/ivpusic/golog.(*Logger).Debug(0xc208010150, 0x6d4780, 0xc2080d8190, 0x0, 0x0, 0x0)
	/home/xi/go/src/github.com/ivpusic/golog/logger.go:241 +0xc5
github.com/ivpusic/neo.(*Static).match(0xc208038208, 0xc20806c5c5, 0x2b, 0x0, 0x0, 0x0, 0x0)
	/home/xi/go/src/github.com/ivpusic/neo/static.go:38 +0x593
github.com/ivpusic/neo.(*Application).ServeHTTP(0xc20806c480, 0x7f182009c750, 0xc2080940a0, 0xc208034750)
	/home/xi/go/src/github.com/ivpusic/neo/application.go:87 +0x1ee
net/http.serverHandler.ServeHTTP(0xc2080bd2c0, 0x7f182009c750, 0xc2080940a0, 0xc208034750)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208116320)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
exit status 2

**Comment by xi3** [comment]
when file not existed serving static files,
the issue only recreated when new logger setting is "DEBUG" (config.toml)
```
[neo]
  [neo.logger]
  level = "DEBUG"
```

and cannot be recreated by "INFO"
```
[neo]
  [neo.logger]
  level = "INFO"
```

**Comment by ivpusic** [comment]
Thank you for reporting error. I couldn't reproduce error on my mashine, but from stacktrace it seems that tabwriter was causing error. It should be fixed by this commit https://github.com/ivpusic/golog/commit/7b10849691154d0fb65cd7da039c03a488642cf7. Can you please check if error is gone after getting new version of golog.

**Comment by xi3** [comment]
Thanks very much, it worked after 
```
go get -u github.com/ivpusic/golog
```
